name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
env:
  TF_VERSION: 1.28
  
defaults:
  run: 
    shell: bash
    working-directory: "v1_infra/"
  
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
          
