name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - v1_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
env:
  TF_VERSION: 1.2.8
  AWS_REGION: ap-northeast-1
  
defaults:
  run: 
    shell: bash
    working-directory: "v1_infra/"
  
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      - name: format
        run: |
          terraform fmt --check
          # --checkをつけることでfmtが正しければ正常終了の0を返し、fmtが正しくなければ0以外を返すのでエラーとなる
      - name: aws credencial setup
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: terraform init
        run: | 
          terraform init -no-color
      - name: terraform validate
        run: |
          terraform validate -no-color